controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    state: active  # Cargar y activar al inicio

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    publish_tf: true
    wheel_separation: 0.17
    wheel_radius: 0.0325
    publish_odom_tf: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    state: active
    position_feedback: true
    integrate_position_from_velocity: true
    use_stamped_vel: false
    enable_odom_tf: true

    #linear.x.has_velocity_limits: true
    #linear.x.max_velocity: 0.3
    #linear.x.min_velocity: -0.3
    #linear.x.has_acceleration_limits: true
    #linear.x.max_acceleration: 0.8
    
    #angular.z.has_velocity_limits: true
    #angular.z.max_velocity: 1.0
    #angular.z.min_velocity: -1.0
    #angular.z.has_acceleration_limits: true
    #angular.z.max_acceleration: 1.5
    
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
