/**:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.3
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.8
    enable_button: 4
    enable_turbo_button: 5
    scale_linear_turbo:
      x: 0.5
    scale_angular_turbo:
      yaw: 1.5